AllCops:
  NewCops: enable
Documentation:
  Enabled: false
Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'db/*'
    - 'db/migrate/*'
    - 'lib/tasks/auto_annotate_models.rake'
Layout/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 40
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/HashSyntax:
  Exclude:
    - 'db/schema.rb'
Layout/SpaceAroundOperators:
  Exclude:
    - 'db/schema.rb'
Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'db/schema.rb'
